#! /bin/bash

set -eu

curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/avhost/docker-go-avbot/trigger/b7b4850f-96c7-435e-b077-f4de515d1e26/  

